### PR TITLE
Fix/issue27

### PR DESCRIPTION
**Pull request by davleh**

### CODE REVIEW

**Comment by davleh** [comment]
@GeorgMeyer23 @ain Could someone please review and merge if ok. I need this tomorrow morning latest.

**Comment by ain** [comment]
I'll give it a go in a bit, in CT. I have another bug suspect actually, but a different topic.

**Comment by davleh** [comment]
@ain, @GeorgMeyer23 I merged it myself as i need it for the dom relaunch urgently

**Comment by ain** [comment]
No probs, I’ll go after you with a bug, if it breaks on CT. Sorry, I’ve had no time yet.

**Comment by ain** [comment]
CT is safe, this change did not break anything. Existing bugs remained though.

**Pull request merged**
